services:
  mongo:
    image: mongo:8.0
    container_name: asana-replicator-db
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db

  # this is used for the queues
  cache:
    image: bitnami/redis:7.4
    container_name: asana-replicator-cache
    restart: unless-stopped
    ports:
      - "6380:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - cache:/data

volumes:
  mongo-data:
  cache:
